config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "countries#index"
  resources :users, only: [:edit, :update]
  resources :countries, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create, :destroy, :show, :edit, :update]do
      resources :comments, only: :create
  end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :message
end

app/models/country.rb
class Country < ApplicationRecord
  
  has_many :users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/country_user.rb
class CountryUser < ApplicationRecord
 
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :country
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :text, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  
  has_many :countries
  has_many :messages
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create(comment_params)
    @message = Message.all
    redirect_to request.referer
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, message_id: params[:message_id])
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :name

  def index
    @country = Country.all
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(country_params)
    if @country.save
      redirect_to root_path
    else
      render :new
    end
  end

  

  def destroy
    country = Country.find(params[:id])
    country.destroy
    redirect_to root_path
  end

  private

  def country_params
    params.require(:country).permit(:name).merge(user_id: current_user.id)
  end

  def name
    @name = Country.all
  end
  

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :name

  def index
    @message = Message.new
    @country = Country.find(params[:country_id])
    @messages = @country.messages.includes(:user).order("created_at DESC")
  end

  def create
    @country = Country.find(params[:country_id])
    @message = @country.messages.new(message_params)
    if @message.save
      redirect_to country_messages_path(@country)
    else
      @messages = @country.messages.includes(:user)
      render :index
    end
  end

  def show
    @country = Country.find(params[:country_id])
    @message = Message.find(params[:id])
    @messsages = @country.messages.includes(:user)
    @comment = Comment.new
    @comments = @message.comments.includes(:user)
  end

  def destroy
    message = Message.find(params[:id])
    message.destroy
  end

  def edit
    @country = Country.find(params[:country_id])
    @message = Message.find(params[:id])
  end

  def update
    @message = Message.find(params[:id])
    @message.update(message_params)
  end



  private

  def message_params
    params.require(:message).permit(:title, :text, :image).merge(user_id: current_user.id)
  end

  def name
    @name = Country.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    current_user.update(user_params)
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/countries/index.html.erb
<div class='wrapper'>
  
  <div class='side-bar'>

    <%= render "messages/side_bar" %>

  </div>
  <div class="title">
  <div class="title-japanese">
  <p>旅を共有しよう。</p>
  </div>
  <div class="title-english">
  <p>　-Would you share your travel?-</p>
  </div>
  </div>
  <% if user_signed_in? %>
  <div class="create-country">
    <%= link_to "New Country", new_country_path %>
  </div>
  <div class="create-country-message">
    <p>※もし、投稿したい国がない場合は作成してください。</p>
    <p>　　If country doesn't exist, please make a room.</p>
    </div>
    
    

  <% else %>
  <div class="user-session">
    <%= link_to "Log in", new_user_session_path, class: "post" %>
    <%= link_to "Sign up", new_user_registration_path, class: "post" %>
  </div>
  <% end %>
</div>

app/views/countries/new.html.erb
<div class='chat-room-form'>
  <h1>new country</h1>
  <%=form_with model: @country, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :国名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'Type a Country'%>
      </div>
    </div>
    
    
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ttt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @country.name %>
    </div>
  </div>

  <div class="right-header">
      <div class="create-country-box">
        <% if user_signed_in? %>
          <div class="create-country-header">
            <%= link_to "New Country", new_country_path %>
          </div>
        <% end %>
      </div>
      

      <div class="close-country">
        <% if user_signed_in? && current_user.id == @country.user_id %>
          <div class="header-button">
            <%= link_to "CLOSE Country", country_path(@country), method: :delete %>
          </div>
        <% end %>
      </div>
  

      
      
    </div>
  </div>

<div class="messages-wrapper">
    <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model: [@country, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :title, class: 'form-message1', placeholder: 'type a title' %>
    <%= f.text_field :text, class: 'form-message2', placeholder: 'type a text' %>
    <label class="form-image">
      <span class="image-file">file</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit 'SEND', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.name %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-title">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= message.title %>
    </div>
    <div class="message-text">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= message.text %>
    </div>
    <%= link_to country_message_path(@country, message.id) do %>
    <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
    <% end %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <% if user_signed_in? %>
      <div class="user-name">
        <%= link_to current_user.name, edit_user_path(current_user) %>
      </div>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <div class="user">
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'btn'%>
    </div>
  <% end %>

</div>


<div class="countries">
<% if user_signed_in? %>
  <p><%= link_to "Country List", root_path, class: 'create-index' %></p> 
    <% @name.each do |country| %>
      <div class="country">
        <div class="country-name">
          <%= link_to country.name, country_messages_path(country) %>
        </div>
      </div>
    <% end %>
  <% end %>
  
</div>

app/views/messages/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/messages/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
      <%#= form_with model: [@country, @message], class: 'form', local: true do |f| %>
      <div class="form-input">
      <%#= f.text_field :title, class: 'form-message', placeholder: 'type a title' %>
      <%#= f.text_field :text, class: 'form-message', placeholder: 'type a text' %>
      <label class="form-image">
      <span class="image-file">画像</span>
      <%#= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%#= f.submit '送信', class: 'form-submit' %>
<%# end %>
</div>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/messages/show.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>

  <div class="message_show">
    <div class="image-opacity">
      <div class="chat-header">
        <div class="left-header">
          <div class="header-title">
            <%= @country.name %>
          </div>
        </div>

        <div class="right-header">
          <% if user_signed_in? && current_user.id == @country.user_id %>
            <div class="header-button">
              <%= link_to "CLOSE Country", country_path(@country), method: :delete %>
            </div>
          <% end %>
        </div>
    
        
      </div>

      <div class="message-box">

        <div class="message-item">

        <div class="message-item-left">
          <h2 class="name">
            <p>TITLE</p>
            <%= @message.title %>
          </h2>
        

          <div class="message-img-content">
            <%= image_tag @message.image.variant(resize: '500x500'), class:"message-box-img" %>
          </div>
        
          <div class="message-explain-box">
            <p>TEXT</p>
            <span><%= @message.text %></span>
          </div>

          <div class="item-choice">
            <% if user_signed_in? && current_user.id == @message.user_id %>
            <%#= link_to "編集", edit_country_message_path(@message.id), method: :get, class: "item-red-btn" %>
            <%#<p class="or-text">or</p>%>
            <%= link_to "DELETE", country_message_path(@message.id), method: :delete, class:"item-destroy" %>
            <% end %>
          </div>
      
          <div class="container">
            <% if user_signed_in? %>
            <%= form_with(model: [@country, @message, @comment], local: true) do |form| %>
            <%= form.text_area :text, placeholder: "type a comment", rows: "2" %>
              <div class="submit-comment">
                <%= form.submit "SEND" %>
              </div>
              <% end %>
            <% else %>
              <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
            <% end %>
          </div>
        </div>
      
        <div class="message-item-right">
          <div class="comments">
            <h4>＜Comments＞</h4>
            <% @comments.each do |comment| %>
            <p>
              <strong><%= comment.user.name %>：</strong>
              <%= comment.text %>
            </p>
            <% end %>
          </div>
        </div>

      </div>
    </div>
  <div>
</div>

app/views/messages/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>